version: 2.1
jobs:
  deploy-production:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - run:
          name: Criando Arquivo SSH.
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh
            touch ~/.ssh/known_hosts
      - run:
          name: Adicionando o IP do servidor ativo aos hosts conhecidos.
          command: |
            ssh-keyscan ec2-18-222-48-205.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy APP
          command: |
            ssh ubuntu@ec2-18-222-48-205.us-east-2.compute.amazonaws.com "cd projects/alexaskill-register-point/;
            git reset --hard ;
            git pull;
            cd backend/;
            killall node;
            node src/server.js;"
workflows:
  build-and-deploy:
    jobs:
      - deploy-production:
          filters:
            branches:
              only: main
